# Generated by Django 3.2.15 on 2022-08-25 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_snippet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
