# Generated by Django 3.2.15 on 2022-08-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testing',
            name='day',
            field=models.IntegerField(),
        ),
    ]
