# Generated by Django 3.2.15 on 2022-08-30 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_companytesting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companytesting',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
        migrations.DeleteModel(
            name='testing',
        ),
        migrations.DeleteModel(
            name='CompanyTesting',
        ),
    ]
