# Generated by Django 3.2.15 on 2022-09-04 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_neuraldroptask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuraldroptask',
            name='company_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
