# Generated by Django 3.2.15 on 2022-09-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_neuraldroptask_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuraldroptask',
            name='AiFilepathtoCompress',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
