# Generated by Django 3.2.15 on 2022-09-04 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_neuraldroptask_aifilepathtocompress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NeuralDropTask',
        ),
    ]
