# Generated by Django 3.2.15 on 2022-09-04 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_delete_neuraldroptask'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeuralDropTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Taskname', models.CharField(max_length=100, unique=True)),
                ('dateofuse', models.DateTimeField(auto_now_add=True)),
                ('AiFilenametoCompress', models.TextField()),
                ('AiFilepathtoCompress', models.FileField(null=True, upload_to='')),
                ('company_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
