# Generated by Django 3.2.15 on 2022-09-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_neuraldroptasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='industry',
        ),
        migrations.AddField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(default='', max_length=30),
        ),
    ]
