# Generated by Django 3.2.15 on 2022-09-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_user_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestingTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Taskname', models.CharField(max_length=100, unique=True)),
                ('dateofuse', models.DateTimeField(auto_now_add=True)),
                ('AiFilenametoCompress', models.TextField()),
                ('AiFilepathtoCompress', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
