# Generated by Django 3.2.15 on 2022-09-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20220915_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testingtasks',
            name='AiFilepathtoCompress',
            field=models.FileField(upload_to=''),
        ),
    ]
