# Generated by Django 3.2.15 on 2022-09-22 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_testingtasks_aifilepathtocompress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testingtasks',
            old_name='AiFilepathtoCompress',
            new_name='File',
        ),
    ]
