# Generated by Django 3.2.15 on 2022-09-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_testingtasks_writing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testingtasks',
            name='File',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
