# Generated by Django 3.2.15 on 2022-10-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20221004_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='testingtasks',
            name='Checkbox',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
