# Generated by Django 3.2.15 on 2022-10-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_testingtasks_checkbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('company_uid', models.UUIDField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('commit_date', models.DateField()),
                ('insdustry', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'company_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompressionTech',
            fields=[
                ('tech_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tech_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'compression_tech',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NeuraldropUseHistory',
            fields=[
                ('neuraldrop_use_history_uid', models.UUIDField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=100)),
                ('date_of_use', models.DateField()),
                ('ai_file_name_to_compress', models.CharField(max_length=100)),
                ('ai_file_path_to_compress', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'neuraldrop_use_history',
                'managed': False,
            },
        ),
    ]
