# Generated by Django 3.2.15 on 2022-10-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_companyinfo_compressiontech_neuraldropusehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeuraldropUseResult',
            fields=[
                ('neuraldrop_use_result_uid', models.UUIDField(primary_key=True, serialize=False)),
                ('compressed_ai_name', models.CharField(max_length=100)),
                ('compressed_ai_file_path', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'neuraldrop_use_result',
                'managed': False,
            },
        ),
    ]
