# Generated by Django 3.2.15 on 2022-10-11 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_remove_neuraldroptasks_aifilepathtocompress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neuraldroptasks',
            name='AiFilenametoCompress',
        ),
    ]
