# Generated by Django 3.2.15 on 2022-10-18 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20221017_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neuraldroptasks',
            name='Checkbox',
        ),
        migrations.RemoveField(
            model_name='neuraldroptasks',
            name='File',
        ),
        migrations.RemoveField(
            model_name='neuraldroptasks',
            name='FileType',
        ),
    ]
