# Generated by Django 3.2.15 on 2022-10-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20221018_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='neuraldroptasks',
            name='state',
            field=models.CharField(default='null', max_length=10),
        ),
    ]
