# Generated by Django 3.2.15 on 2022-10-18 12:53

import api.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_neuraldroptasks_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testingtasks',
            name='File',
            field=models.FileField(null=True, upload_to=api.users.models.user_directory_path),
        ),
    ]
