# Generated by Django 3.2.15 on 2022-10-18 13:09

import api.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_alter_testingtasks_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='neuraldroptasks',
            name='Checkbox',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='neuraldroptasks',
            name='File',
            field=models.FileField(null=True, upload_to=api.users.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='neuraldroptasks',
            name='FileType',
            field=models.CharField(default='file', max_length=50),
        ),
    ]
