# Generated by Django 3.2.15 on 2022-10-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_auto_20221018_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuraldroptasks',
            name='Taskname',
            field=models.CharField(max_length=100),
        ),
    ]
