# Generated by Django 3.2.15 on 2022-10-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_alter_neuraldroptasks_taskname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuraldroptasks',
            name='Taskname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
