# Generated by Django 3.2.15 on 2022-10-26 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_neuraldroptasks_checkbox1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neuraldroptasks',
            old_name='Checkbox',
            new_name='Checkbox2',
        ),
    ]
