# Generated by Django 3.2.15 on 2022-10-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_rename_checkbox_neuraldroptasks_checkbox2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuraldroptasks',
            name='Checkbox1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='neuraldroptasks',
            name='Checkbox2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
