# Generated by Django 3.2.15 on 2022-10-27 12:25

import api.users.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_auto_20221026_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Taskname', models.CharField(max_length=100)),
                ('userId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(null=True, upload_to=api.users.models.user_directory_path)),
                ('taskId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.tasks')),
            ],
        ),
    ]
