# Generated by Django 3.2.15 on 2022-10-28 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_file_company_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='neuraldroptasks',
            name='File',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
