# Generated by Django 3.2.15 on 2022-10-31 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_alter_task_taskname'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='Checkbox1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='Checkbox2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='FileType',
            field=models.CharField(default='file', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='taskId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.task'),
        ),
        migrations.AlterField(
            model_name='file',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
