# Generated by Django 3.2.15 on 2022-10-31 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_auto_20221031_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Performance', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Parameter', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Size', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Computation', models.DecimalField(decimal_places=1, max_digits=3)),
                ('TaskId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.task')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedTech6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Performance', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Parameter', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Size', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Computation', models.DecimalField(decimal_places=1, max_digits=3)),
                ('TaskId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.task')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedTech5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Performance', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Parameter', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Size', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Computation', models.DecimalField(decimal_places=1, max_digits=3)),
                ('TaskId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.task')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedTech4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Performance', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Parameter', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Size', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Computation', models.DecimalField(decimal_places=1, max_digits=3)),
                ('TaskId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.task')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedTech3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Performance', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Parameter', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Size', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Computation', models.DecimalField(decimal_places=1, max_digits=3)),
                ('TaskId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.task')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedTech2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Performance', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Parameter', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Size', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Computation', models.DecimalField(decimal_places=1, max_digits=3)),
                ('TaskId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.task')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedTech1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Performance', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Parameter', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Size', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Computation', models.DecimalField(decimal_places=1, max_digits=3)),
                ('TaskId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.task')),
            ],
        ),
    ]
