# Generated by Django 3.2.15 on 2022-11-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_recommendedtech1_recommendedtech2_recommendedtech3_recommendedtech4_recommendedtech5_recommendedtech'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedtech1',
            name='File',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='recommendedtech2',
            name='File',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='recommendedtech3',
            name='File',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='recommendedtech4',
            name='File',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='recommendedtech5',
            name='File',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='recommendedtech6',
            name='File',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='resulttech',
            name='File',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
