# Generated by Django 3.2.15 on 2022-11-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_contactus_jobtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='jobTitle',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
